### PR TITLE
rc/v0.6.0

### PR DESCRIPTION
**Pull request by duanyytop**
* Rename RPC response type
* Implement asw wallet which include account, balance and transferring

### CODE REVIEW

**Comment by ashchan** [comment]
@duanyytop Please add `v0.6.0` entries to `CHANGLOG.md`.

**Comment by ashchan** [comment]
Changed base branch to `master`.

**Comment by duanyytop** [comment]
I always merge or rebase from develop branch to my fork. I guess some changes don't merge or rebase to my fork in time. I do it now.

**Comment by duanyytop** [comment]
I merge the develop branch latest code from nervosnetwork to my fork and rebase develop to rc/v0.6.0.

**Comment by ashchan** [comment]
> I merge the develop branch latest code from nervosnetwork to my fork and rebase develop to rc/v0.6.0.

CI is failing. Could you check that?

**Pull request merged**
