### PR TITLE
Refactor module name

### PR DESCRIPTION
**Pull request by duanyytop**
* Rename  console module to ckb-sdk
* Move example files to example moudle
* Rename core module to ckb

### CODE REVIEW

**Comment by quake** [comment]
This is a breaking change, I suggest that we should change the version to `0.25.0`

**Comment by duanyytop** [comment]
> This is a breaking change, I suggest that we should change the version to `0.25.0`

We keep sdk version be same with ckb now,  0.25  should be the next big version.  So we may put this change to next big version.

**Comment by quake** [comment]
> > This is a breaking change, I suggest that we should change the version to `0.25.0`
> 
> We keep sdk version be same with ckb now, 0.25 should be the next big version. So we may put this change in next big version.

Get, LGTM

**Comment by ashchan** [comment]
> This is a breaking change, I suggest that we should change the version to `0.25.0`

SDKs follow CKB main version.

**Pull request merged**
